### ISSUE TITLE
Cmake "ArcGIS Runtime 100.8 Qt Quick app" template runtime problem

### ISSUE THREAD

**Issue by jensdenbraber** [Esri/arcgis-runtime-toolkit-qt#368]
On windows: when selecting "ArcGIS Runtime 100.8 Qt Quick app" from the Qt creator wizard and selecting Cmake as buildssystem, where I set the following Cmake values:

- ArcGISRuntime_EsriCommonQt_IMPLIB = C:\ArcGIS\Qt100.8\sdk\windows\x64\lib\EsriCommonQtd.lib
- ArcGISRuntime_EsriCommonQt_LIB = C:\ArcGIS\Qt100.8\sdk\windows\x64\bin\EsriCommonQtd.dll
- ArcGISRuntime_runtimecore_LIB = C:\ArcGIS\Qt100.8\sdk\windows\x64\bin\runtimecore.dll
- ArcGISRuntime_INSTALL_DIR = C:/ArcGIS/Qt100.8
- QML_IMPORT_PATH = C:/ArcGIS/Qt100.8/sdk/windows/x64/qml

 I keep getting the following error during runtime debugging:

> QQmlApplicationEngine failed to load component
> qrc:/qml/main.qml:16 plugin cannot be loaded for module "Esri.ArcGISRuntime": Cannot load library C:\ArcGIS\Qt100.8\sdk\windows\x64\qml\Esri\ArcGISRuntime\ArcGISRuntimePlugind.dll: The specified procedure could not be found.

How can I fix this? Would it be possible to fix this in the "ArcGIS Runtime 100.8 Qt Quick app" template?

**Comment by ldanzinger** [comment]
@jensdenbraber can you please post this question on our [GeoNet forum](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-qt) instead? We like to keep this repo's issues to be specific to our toolkit, whereas the issue you mention is with the Runtime API itself. Thank you

**Comment by jensdenbraber** [comment]
alright, I posted it here: [https://community.esri.com/message/928916](https://community.esri.com/message/928916)
