### ISSUE TITLE
How to Rezise scale bar when i Zoom in and Zoom out 

### ISSUE THREAD

**Issue by SushmaMP13** [Esri/arcgis-runtime-toolkit-qt#378]
i have made a custom scale bar similar to https://community.esri.com/thread/201990-scale-bar , i am trying to resize the scale bar when i zoom in and zoom out .

**Comment by ldanzinger** [comment]
Can you update the size of your scale bar whenever MapView.onViewpointChanged emits? https://developers.arcgis.com/qt/latest/qml/api-reference/qml-esri-arcgisruntime-geoview.html

**Comment by SushmaMP13** [comment]
I have a MapView and scale bar like:
```
MapView {
 
        ScaleBar{
            anchors.left: mapView.left
            anchors.bottom: mapView.bottom
            anchors.bottomMargin: 80
            anchors.margins: 10 * scaleFactor
            map:mapView
        }

onViewpointChanged {


        }
}

```
Do i need to set Width of scale bar on onViewpointChanged ? if so how can i find width dynamically? 
Rightnow width has been set inside ScaleBar.qml 

![SCALE_BAR](https://user-images.githubusercontent.com/68109250/87168649-1c7a0900-c2cf-11ea-9a80-d0e1bd9959ea.png)

**Comment by SushmaMP13** [comment]
Got solution by setting map.scale to the width of scale bar
