### ISSUE TITLE
Error trying Portal Items View example

### ISSUE THREAD

**Issue by jf990** [Esri/arcgis-runtime-toolkit-qt#66]
Loaded the Portal Items View example then scrolled to the World Traffic Service item when trying to load that layer I get the error

qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get0_next_proto_negotiated

**Comment by ldanzinger** [comment]
@jf990 what platform are you on? I don't get that error on Mac or Windows, but if you are on Windows, you will probably need to get the OpenSSL binaries, which you can either build from source or grab from [here](http://www.openssl.org/about/binaries.html).

As far as the example, the world traffic layer requires AGOL credentials, whereas all of the other layers do not. That is why all the other layers that appear from the portal search work, but this one does not. So an optional fix would be to have a user credential dialog appear at the beginning, and then to apply those credentials to the layer.

**Comment by jf990** [comment]
I am trying this on OS X Yosemite. I just noticed I get tls and ssl errors when I run any Qt project so there must be something wrong with my configuration for qt.network.ssl, so it is probable the issue has nothing to do with ssl I just assumed so since I got no map but got that error when i requested it.

**Comment by ldanzinger** [comment]
@jf990 thanks for notifying of the issue. I removed the ability to add the portal item to the map. The point of the example is to simply show the portal item viewer, and so adding in functionality like creating different types of layers (the traffic one is a dynamic, not tiled service) and setting user credentials is complicating what the example is trying to show. Let me know if you have any questions.
