### ISSUE TITLE
null object when clicking position navbar button in PortalItemsView sample

### ISSUE THREAD

**Issue by jf990** [Esri/arcgis-runtime-toolkit-qt#67]
PortalItemsView sample shows the NavigationToolbar but does not init a positionSource, so requesting PositionButton.onClicked produces an error

QmlSamplesApp.app/Contents/Resources/qml/ArcGIS/Runtime/Toolkit/Controls/PositionButton.qml:41: TypeError: Cannot read property 'active' of null

**Comment by ldanzinger** [comment]
I have removed the navigation toolbar from this example, as the point of this example was simply to show how to use the toolkit portal item viewer component. Thanks for notifying of the issue.
