### ISSUE TITLE
SearchBox example initial text issue

### ISSUE THREAD

**Issue by jf990** [Esri/arcgis-runtime-toolkit-qt#68]
SearchboxExample.qml sets SearchBox with searchTextInput: "900 North Point Ave, San Francisco", but search control renders with its internal default of "3575 Geary Blvd, San Francisco". Without typing in anything and clicking search it locates 900 North Point Ave, which is not what the user wanted but it is what the code wanted. Altering the text after init produces the correct results.

**Comment by ldanzinger** [comment]
@jf990 I switched the initial text and fixed some code issues. Can you please test?

**Comment by jf990** [comment]
Tested. the demo locates the same address the SearchBox is initialized with.
thanks for fixing this!
