### ISSUE TITLE
SearchboxExample.qml using incorrect status check

### ISSUE THREAD

**Issue by jf990** [Esri/arcgis-runtime-toolkit-qt#69]
onFindStatusChanged is not catching the find results although the status change is signaled with 2. it appears findStatus === Locator.FindComplete is not working. I think it should be findStatus === Enums.FindStatusCompleted. (Likewise for the error condition)

**Comment by ldanzinger** [comment]
@jf990 this should be fixed now. Can you please pull the latest and test?

**Comment by jf990** [comment]
I tested these changes, working great now. thanks!

**Comment by ldanzinger** [comment]
:+1:
